name: jupyterlite-sphinx-dev
channels:
    - conda-forge
dependencies:
    - pip
    - jupyter_server
    - jupyterlab_server
    - pydata-sphinx-theme
    - docutils
    - sphinx
    - black
    - pip:
        - jupyterlite-core==0.1.0b19
        - jupyterlite-pyodide-kernel==0.0.5

