name: jupyterlite-sphinx-dev
channels:
    - conda-forge
dependencies:
    - pip
    - jupyter_server
    - jupyterlab_server
    - jupyterlite-core >=0.1.0,<0.2
    - pydata-sphinx-theme
    - docutils
    - sphinx
    - black
    - pip:
        - .
        - jupyterlite-xeus-python >=0.8.1,<0.9.0
