name: jupyterlite-sphinx-dev
channels:
    - conda-forge
dependencies:
    - pip
    - jupyter_server
    - jupyterlab_server
    - jupyterlite-xeus >=0.1.8,<0.2.0
    - jupyterlite-core >=0.3,<0.4
    - pydata-sphinx-theme
    - myst-parser
    - docutils
    - sphinx
    - black
    - voici
    - pip:
        - .
