name: jupyterlite-sphinx-dev
channels:
  - conda-forge
dependencies:
  - pip
  - jupyter_server
  - jupyterlab_server
  - jupyterlite-core >=0.3,<0.8
  - jupytext
  - pydata-sphinx-theme
  - micromamba=2.0.5
  - myst-parser
  - docutils
  - sphinx
  - black
  - voici
  - pip:
      - .
      - jupyterlite-xeus >=2.1.2
